### ISSUE TITLE
pinDef don't work in class test

### ISSUE THREAD

**Issue by nobertomaciel** [guaacoelho95/OPGCC008-Problema2#6]
Pode ter sido a mensagem passada, pois, o teste com dois nodes funcionou in home.

**Comment by guaacoelho95** [comment]
{"node_master":4208779354,"t_send":5,"send":true,"type":2,"timestamp":123456,"nodeDestiny":4208779354,"pindDef": [1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0]}

**Comment by nobertomaciel** [comment]
Achei a causa do problema... está no nome da chave com uma letra d a mais `{"node_master":4208779354,"t_send":5,"send":true,"type":2,"timestamp":123456,"nodeDestiny":4208779354,"**pindDef**": [1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0]}`
